language: cpp
compiler:
  - gcc

before_install:
  - sudo add-apt-repository "deb http://ppa.launchpad.net/canonical-qt5-edgers/qt5-daily/ubuntu precise main"
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt4-dev-tools g++ > /dev/null
  - sudo apt-get install qtdoc
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: 
  - bash ./UnitTest/Travis/make.sh
  - bash ./UnitTest/Travis/test.sh
  