language: cpp
compiler:
  - gcc

before_install:
  - sudo add-apt-repository "deb http://ppa.launchpad.net/canonical-qt5-edgers/qt5-daily/ubuntu precise main" > /dev/null 2>&1
  - sudo apt-get update -qq > /dev/null 2>&1
  - sudo apt-get install -qq g++ > /dev/null
  - sudo apt-get install qtbase qttools > /dev/null
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: 
  - /opt/qt5/bin/qmake ZeroMS.pro
  - make
  - export QT_INSTALL_DOCS=/usr/share/qt5/doc && /opt/qt5/bin/qdoc Doc/ZeroMS.qdocconf
  - bash ./UnitTest/Travis/test.sh
